### PR TITLE
Link Unikname when wallet is a delegate

### PR DESCRIPTION
**Pull request by rigwild**
When a wallet is a delegate, link its Unikname page

Result:
https://deploy-preview-60--explorer-uns-network.netlify.app/wallets/D9cH5Jr1gNHUTFrAi8MHmgXVPPHy31bXff

image

### CODE REVIEW

**Comment by dlecan** [comment]
@rigwild thank you for this proposal, we agree with this improvement.

Can you rebase from the `develop` branch? A Github action fails in your PR and a fix is available on it.
I will merge this PR as soon as it is done.

Thank you :pray:

**Comment by rigwild** [comment]
Looks like it still fails! 😅

**Comment by ftreguer** [comment]
> Looks like it still fails!

Hi @rigwild, your branch is out of date, you have to rebase it to pass CI steps :) Can you please pass `yarn lint` to format your code. Thx for your contribution @rigwild !

**Comment by rigwild** [comment]
Might be caused by protected branches, see https://github.com/stefanzweifel/git-auto-commit-action#push-to-protected-branches
Someone had exactly the same issue: https://github.com/actions/checkout/issues/275

**Pull request merged**
